name: Documentation

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Release

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build documentation
        uses: mattnotmitt/doxygen-action@v1.9.5

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
